name: trigger_action

on:
  push:
    branches: ['master', 'main']
  schedule:
    # 매일 한국 시간 오전 9시 (UTC 00:00)
    - cron: '0 0 * * *'
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Node 20 경고 메시지 해결을 위해 LTS 버전 적용
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build TypeScript project
        run: npm run build

      - name: Create .env file
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_REPOSITORY: ${{ secrets.GH_REPOSITORY }}
          PROGRAMMERS_ID: ${{ secrets.PROGRAMMERS_ID }}
          PROGRAMMERS_PW: ${{ secrets.PROGRAMMERS_PW }}
        run: |
          touch .env
          echo "GH_PAT=$GH_PAT" >> .env
          echo "GH_REPOSITORY=$GH_REPOSITORY" >> .env
          echo "PROGRAMMERS_ID=$PROGRAMMERS_ID" >> .env
          echo "PROGRAMMERS_PW=$PROGRAMMERS_PW" >> .env

      - name: Run Programmers Badge Service
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_REPOSITORY: ${{ secrets.GH_REPOSITORY }}
          PROGRAMMERS_ID: ${{ secrets.PROGRAMMERS_ID }}
          PROGRAMMERS_PW: ${{ secrets.PROGRAMMERS_PW }}
        run: |
          node dist/main.js
